services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    volumes:
      - pgData:/var/lib/postgresql/data
    env_file:
      - .env
  node_app:
    container_name: node_app
    build: .
    ports:
      - 1234:4000
    env_file:
      - .env
    depends_on:
      - db

volumes:
  pgData:
