services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    env_file:
      - .env
  node:
    container_name: node
    build: .
    ports:
      - 4000:4000
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres-volume:
